# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/01_etl/00_InternationalPrices/04_GroupAndResample.ipynb.

# %% auto 0
__all__ = ['PANDAS_FREQS']

# %% ../../../nbs/01_etl/00_InternationalPrices/04_GroupAndResample.ipynb 2
from typing import Dict, Union
import pandas as pd

# %% ../../../nbs/01_etl/00_InternationalPrices/04_GroupAndResample.ipynb 3
PANDAS_FREQS = {'W-SUN': 'Weekly frequency (Sundays)',
 'W-MON': 'Weekly frequency (Mondays)',
 'W-TUE': 'Weekly frequency (Tuesdays)',
 'W-WED': 'Weekly frequency (Wednesdays)',
 'W-THU': 'Weekly frequency (Thursdays)',
 'W-FRI': 'Weekly frequency (Fridays)',
 'W-SAT': 'Weekly frequency (Saturdays)'}
