# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/01_etl/00_InternationalPrices/02_Datetime.ipynb.

# %% auto 0
__all__ = ['old_version', 'new_version']

# %% ../../../nbs/01_etl/00_InternationalPrices/02_Datetime.ipynb 2
import os
import pathlib
import pandas as pd
import unidecode

# %% ../../../nbs/01_etl/00_InternationalPrices/02_Datetime.ipynb 3
from etl import tables

# %% ../../../nbs/01_etl/00_InternationalPrices/02_Datetime.ipynb 4
old_version = '01'
new_version = '02'

for table in tables.international_list:

    df = pd.read_csv(
        table.version(old_version),
        low_memory=False,
    )

    df['date'] = pd.to_datetime(
        df['fecha'],
        infer_datetime_format=True,
    )
    df.drop(columns=['fecha'],inplace=True)
    df.set_index('date', inplace=True)


    df.to_csv(table.version(new_version))
