# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/01_etl/00_InternationalPrices/03_RowTransformations.ipynb.

# %% auto 0
__all__ = ['old_new_cols', 'old_version', 'new_version']

# %% ../../../nbs/01_etl/00_InternationalPrices/03_RowTransformations.ipynb 4
import re
import os
import pathlib
import pandas as pd
import unidecode

from etl import tables

old_new_cols = {
    "mercancia": "category",
    "ciudad": "city",
    "paquete": "package",
    "preciominimo": "min_price",
    "precioalto": "high_price",
    "temporada": "season",
    "tamanio": "size",
    "tonoDemanda": "demand_tone",
    "BaseVenta": "sales_type",
    "tonoMercado": "market_tone",
    "comentarios": "comments",
    "CiudadRpt": "city_rpt",
    "date": "date",
}

old_version = '02'
new_version = '03'

for table in tables.international_list:

    df = pd.read_csv(table.version(old_version))
    df = df[old_new_cols.keys()]
    df.columns = old_new_cols.values()

    df['min_price'] = pd.to_numeric(df['min_price'], errors='coerce')
    df['high_price'] = pd.to_numeric(df['high_price'], errors='coerce')

    # df['price'] = (1 / 2.)*(df['min_price'] + df['high_price'])
    df['price'] = df[['min_price', 'high_price']].mean(axis=1)
  
    df['category'] = df['category'].apply(lambda x: re.sub(r"\s+", "_", str(x)))
    df['category'] = df['category'].apply(lambda x: re.sub(r",+", "", str(x)))
    df['category'] = df['category'].apply(lambda x: str(x).lower())
    # df['organic'] = df['tipo'].apply(lambda x: x == 'Organic')

    # # df['product'] = df['variedad'] + ' ' + df['subvariedad']

    # # df.drop(columns=['tipo', 'mercancia', 'variedad', 'subvariedad'])

    df.to_csv(table.version(new_version), index=False)
