# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_national/99_util/02_Constants.ipynb.

# %% auto 0
__all__ = ['PROJECT_PATH', 'DATA_PATH', 'PLOTLY_THEME', 'PANDAS_FREQS', 'ARIMA_MAX_STEPS', 'SMES_MAX_STEPS',
           'PERCENTAGE_CONFIDENCE_INTERVAL']

# %% ../../nbs/02_national/99_util/02_Constants.ipynb 2
from pathlib import Path
from os import path
from national import util

# %% ../../nbs/02_national/99_util/02_Constants.ipynb 3
PROJECT_PATH = Path('/', 'wd')
DATA_PATH = Path(PROJECT_PATH)

PLOTLY_THEME= 'plotly_white'

# %% ../../nbs/02_national/99_util/02_Constants.ipynb 7
_DAYS_ABBR = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']
_DAY_LONG = [
    'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'
]

PANDAS_FREQS = {
    f"W-{x}": f"weekly frequency ({y}s)" for x, y in zip(_DAYS_ABBR, _DAY_LONG)
}

# %% ../../nbs/02_national/99_util/02_Constants.ipynb 9
ARIMA_MAX_STEPS = 60
SMES_MAX_STEPS = 60

# PERCENTAGE_TEST_DATASET_FOR_MAX_STEPS = 0.7

# %% ../../nbs/02_national/99_util/02_Constants.ipynb 10
PERCENTAGE_CONFIDENCE_INTERVAL = {
    50: 0.67,
    55: 0.76,
    60: 0.84,
    65: 0.93,
    70: 1.04,
    75: 1.15,
    80: 1.28,
    85: 1.44,
    90: 1.64,
    95: 1.96,
    96: 2.05,
    97: 2.17,
    98: 2.33,
    99: 2.58,
}
