# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_national/04_TimeSeries/01_SetAndProcess.ipynb.

# %% auto 0
__all__ = ['time_series']

# %% ../../nbs/02_national/04_TimeSeries/01_SetAndProcess.ipynb 2
from typing import Dict, Union,Optional

import pandas as pd

# %% ../../nbs/02_national/04_TimeSeries/01_SetAndProcess.ipynb 3
def time_series(
    df: pd.DataFrame,
    time_column: str,
    freq: Union[str, list],
    agg_method: Union[str, dict],
) -> Union[pd.DataFrame, Dict[str, pd.DataFrame]]:

    cols = [x for x in agg_method.keys()]
    cols.append(time_column)
    ts = df[cols]

    ts.set_index(
        time_column,
        inplace=True,
    )

    if type(freq) == str:
        ts = ts.resample(freq).agg(agg_method)
    elif type(freq) == list:
        ts = {f: ts.resample(f).agg(agg_method) for f in freq}

    return ts
