# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/02_national/01_DataPreprocessing/01_Load.ipynb.

# %% auto 0
__all__ = ['Data']

# %% ../../../nbs/02_national/01_DataPreprocessing/01_Load.ipynb 3
from pathlib import Path
import pandas as pd
from .. import tables

# %% ../../../nbs/02_national/01_DataPreprocessing/01_Load.ipynb 4
class Data:
    """
    Loads the data
    """

    def __init__(self,
                 data_path: str = tables.granos_historico.version('04_W-MON'),
                 **args):
        super().__init__(**args)

        self.df = pd.read_csv(data_path)

        self.df['date'] = pd.to_datetime(
            self.df['date'])
