# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/01_etl/00_NationalPrices/04_GroupAndResample.ipynb.

# %% auto 0
__all__ = ['PANDAS_FREQS', 'old_version', 'freq', 'new_version', 'table']

# %% ../../../nbs/01_etl/00_NationalPrices/04_GroupAndResample.ipynb 2
from typing import Dict, Union
import pandas as pd

# %% ../../../nbs/01_etl/00_NationalPrices/04_GroupAndResample.ipynb 3
PANDAS_FREQS = {'W-SUN': 'Weekly frequency (Sundays)',
 'W-MON': 'Weekly frequency (Mondays)',
 'W-TUE': 'Weekly frequency (Tuesdays)',
 'W-WED': 'Weekly frequency (Wednesdays)',
 'W-THU': 'Weekly frequency (Thursdays)',
 'W-FRI': 'Weekly frequency (Fridays)',
 'W-SAT': 'Weekly frequency (Saturdays)'}

# %% ../../../nbs/01_etl/00_NationalPrices/04_GroupAndResample.ipynb 4
import os
import pathlib
import pandas as pd
import unidecode

from .. import tables

old_version = '03'
freq = 'W-MON'
new_version = '04_'+freq

table: tables.Table

for table in tables.national_list:

    df = pd.read_csv(
        table.version(old_version),
        low_memory=False,
    )

    df['date'] = pd.to_datetime(df['date'], )
    
    
    df.set_index(['state', 'product', 'date'], inplace=True)
    df.sort_values(['state', 'product', 'date'], inplace=True)

    level_values =  [df.index.get_level_values(i) for i in [0, 1]] 

    result = df.groupby(
       level_values + [pd.Grouper(freq=freq, level=-1)]
    ).agg(
        {
            'min_price': min,
            'max_price': max,
            'price': 'mean', 
            'import': 'first'
        }
    )
    
    result.to_csv(table.version(new_version))
    
