# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/01_etl/00_NationalPrices/03_RowTransformations.ipynb.

# %% auto 0
__all__ = ['keep_columns', 'new_column_names', 'old_version', 'new_version']

# %% ../../../nbs/01_etl/00_NationalPrices/03_RowTransformations.ipynb 2
import os
import pathlib
import pandas as pd
import unidecode

from .. import tables

# %% ../../../nbs/01_etl/00_NationalPrices/03_RowTransformations.ipynb 3
keep_columns = [
    'producto', 'origen', 'destino', 'date', 'precio_minimo', 'precio_maximo',
    'precio_frecuente'
]

new_column_names = [
    'product', 'source', 'dest', 'date', 'min_price', 'max_price', 'price',
]

 
old_version = '02'
new_version = '03'
for table in tables.national_list:

    df = pd.read_csv(table.version(old_version),low_memory=False)
    df = df[keep_columns]
    
    df.columns = new_column_names
    

    df['state'] = df['dest'].apply(lambda x: x.split(':')[0].strip())
    df['state'] = df['state'].apply(
        lambda x: unidecode.unidecode(x) if x != 'DF' else 'Ciudad de Mexico'
    )

    df['center'] = df['dest'].apply(lambda x: x.split(':')[-1])

    df['import'] = df['source'].apply(lambda x: x == 'Importación')

    #df.drop(columns=['destino'],inplace=True)

    df['min_price'] = pd.to_numeric(df['min_price'], errors='coerce')
    df['max_price'] = pd.to_numeric(df['max_price'], errors='coerce')
    df['price'] = pd.to_numeric(df['price'], errors='coerce')


    # remove mixed types in min and max prices substiting them with price
    df['min_price'].mask(df['min_price'].isnull(), df['price'], inplace=True) 
    df['max_price'].mask(df['max_price'].isnull(), df['price'], inplace=True) 


    df.to_csv(table.version(new_version), index=False)
