# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/niloIQ2',
                'doc_host': 'https://kikejimenez.github.io',
                'git_url': 'https://github.com/kikejimenez/niloIQ2',
                'lib_path': 'niloIQ2'},
  'syms': {'niloIQ2.core': {'niloIQ2.core.foo': ('core.html#foo', 'niloIQ2/core.py')}}}