# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_national/02_EDA/04_MissingValues.ipynb.

# %% auto 0
__all__ = ['bar_plot', 'check']

# %% ../../nbs/02_national/02_EDA/04_MissingValues.ipynb 2
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

from national.util import constants
from IPython.display import display, Markdown

# %% ../../nbs/02_national/02_EDA/04_MissingValues.ipynb 3
def bar_plot(data: pd.DataFrame) -> go.Figure:
    """ 
    Given a dataframe it counts the null values and give a bar plot aith the total null-values
    
    :param data: A pandas dataframe with date information
    :return: A graphic object Figure of type bar for the missing values
    """
    fig = px.bar(data.count().rename('count'))
    fig.update_traces(
        marker_color='#28587B',
        hovertemplate='Feature: %{x}' + '<br> Non-nulls: %{y:5f}',
        name='',
        showlegend=False,
    )
    fig.update_layout(yaxis_title='Counts',
                      xaxis_title='',
                      title='Missing Values - Bar',
                      plot_bgcolor='rgba(0,0,0,0)',
                      template=constants.PLOTLY_THEME,
                      )

    return fig

# %% ../../nbs/02_national/02_EDA/04_MissingValues.ipynb 5
def check(data):
    nb_missing = data.isnull().sum().sum()
    
    if nb_missing == 0:

        text = "There are no missing values. Data is ready to be analyzed"
    else:
        text = f"There {nb_missing} missing values of a total of {len(data)}"

    return display(Markdown(text))
